version: '3.8'

services:
  logger:
    image: registry.digitalocean.com/unihox-live/server-logger:${TAG:-latest}
    container_name: logger
    ports:
      - "3000:3000" # Grafana
      - "3100:3100" # Loki
      - "9080:9080" # Promtail
    volumes:
      - grafana-storage:/var/lib/grafana
      - loki-data:/loki
      - /var/log:/var/log
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    platform: linux/amd64

volumes:
  grafana-storage:
  loki-data: