[supervisord]
nodaemon=true

[program:grafana]
command=/usr/sbin/grafana-server --homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini
autostart=true
autorestart=true
stderr_logfile=/var/log/grafana.err.log
stdout_logfile=/var/log/grafana.out.log

[program:loki]
command=/usr/local/bin/loki -config.file=/etc/loki/config.yaml
autostart=true
autorestart=true
stderr_logfile=/var/log/loki.err.log
stdout_logfile=/var/log/loki.out.log

[program:promtail]
command=/usr/local/bin/promtail -config.file=/etc/promtail/config.yaml
autostart=true
autorestart=true
stderr_logfile=/var/log/promtail.err.log
stdout_logfile=/var/log/promtail.out.log
