[supervisord]
nodaemon=true

[program:grafana]
command=/usr/sbin/grafana-server --homepath=/usr/share/grafana
autostart=true
autorestart=true

[program:loki]
command=/usr/bin/loki -config.file=/etc/loki/config.yaml
autostart=true
autorestart=true
